### ISSUE TITLE
Cannot install cfclient on Mac os 13.2.1.

### ISSUE THREAD

**Issue by razmy-hathy** [bitcraze/crazyflie-clients-python#659]
pip install pyqt5==5.13
ERROR: Could not find a version that satisfies the requirement pyqt5==5.13 (from versions: 5.14.0, 5.14.1, 5.14.2, 5.15.0, 5.15.1, 5.15.2, 5.15.3, 5.15.4, 5.15.5, 5.15.6, 5.15.7, 5.15.8, 5.15.9)
ERROR: No matching distribution found for pyqt5==5.13
razmy@Razmys-MacBook-Pro crazyflie-clients-python % pip3 install cfclient                                                                                        
zsh: /opt/homebrew/bin/pip3: bad interpreter: /opt/homebrew/opt/python@3.11/bin/python3.11: no such file or directory
Collecting cfclient
  Using cached cfclient-2023.2-py3-none-any.whl (307 kB)
Collecting appdirs~=1.4.0
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting pyserial~=3.5
  Using cached pyserial-3.5-py2.py3-none-any.whl (90 kB)
Collecting PyQt5-sip>=12.9.0
  Using cached PyQt5_sip-12.11.1-cp310-cp310-macosx_10_9_universal2.whl (142 kB)
Collecting qasync~=0.23.0
  Using cached qasync-0.23.0-py3-none-any.whl (13 kB)
Collecting pyqtgraph~=0.11
  Using cached pyqtgraph-0.13.2-py3-none-any.whl (955 kB)
Collecting cflib>=0.1.22
  Using cached cflib-0.1.22-py2.py3-none-any.whl (185 kB)
Requirement already satisfied: numpy<1.25,>=1.20 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from cfclient) (1.23.4)
Collecting pyqt5~=5.15.0
  Using cached PyQt5-5.15.9.tar.gz (3.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      Traceback (most recent call last):
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/private/var/folders/gv/0ks42qm54xl17z3xw7hyjz3m0000gn/T/pip-build-env-sa8ycmxq/overlay/lib/python3.10/site-packages/sipbuild/api.py", line 46, in build_wheel
          project = AbstractProject.bootstrap('wheel',
        File "/private/var/folders/gv/0ks42qm54xl17z3xw7hyjz3m0000gn/T/pip-build-env-sa8ycmxq/overlay/lib/python3.10/site-packages/sipbuild/abstract_project.py", line 87, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "/private/var/folders/gv/0ks42qm54xl17z3xw7hyjz3m0000gn/T/pip-build-env-sa8ycmxq/overlay/lib/python3.10/site-packages/sipbuild/project.py", line 585, in setup
          self.apply_user_defaults(tool)
        File "/private/var/folders/gv/0ks42qm54xl17z3xw7hyjz3m0000gn/T/pip-install-3m5u2d2i/pyqt5_67a107b39e5e4cb48902f3ce5b009880/project.py", line 68, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/private/var/folders/gv/0ks42qm54xl17z3xw7hyjz3m0000gn/T/pip-build-env-sa8ycmxq/overlay/lib/python3.10/site-packages/pyqtbuild/project.py", line 70, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/private/var/folders/gv/0ks42qm54xl17z3xw7hyjz3m0000gn/T/pip-build-env-sa8ycmxq/overlay/lib/python3.10/site-packages/sipbuild/project.py", line 236, in apply_user_defaults
          self.builder.apply_user_defaults(tool)
        File "/private/var/folders/gv/0ks42qm54xl17z3xw7hyjz3m0000gn/T/pip-build-env-sa8ycmxq/overlay/lib/python3.10/site-packages/pyqtbuild/builder.py", line 69, in apply_user_defaults
          raise PyProjectOptionException('qmake',
      sipbuild.pyproject.PyProjectOptionException
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

When tried install the I'm getting this error. I also tried the various options such as one given in the following 

 brew uninstall pyqt5
 pip install pyqt5==5.13 

When I try this  I got the below error 

ERROR: Could not find a version that satisfies the requirement pyqt5==5.13 (from versions: 5.14.0, 5.14.1, 5.14.2, 5.15.0, 5.15.1, 5.15.2, 5.15.3, 5.15.4, 5.15.5, 5.15.6, 5.15.7, 5.15.8, 5.15.9)
ERROR: No matching distribution found for pyqt5==5.13

I even tried pip install pyqt5==5.14  , but no luck I got below error.

Collecting pyqt5==5.14
  Using cached PyQt5-5.14.0.tar.gz (3.2 MB)
error: invalid-pyproject-build-system-requires

× Can not process pyqt5==5.14 from https://files.pythonhosted.org/packages/7c/5b/e760ec4f868cb77cee45b4554bf15d3fe6972176e89c4e3faac941213694/PyQt5-5.14.0.tar.gz
╰─> This package has an invalid `build-system.requires` key in pyproject.toml.
    It contains an invalid requirement: 'sip >=5.0.1 <6'

and even I tried install in from source, but I got the same error. Please tried to help me because I need to complete my university project.

**Comment by krichardsson** [comment]
Thanks for the info!

There might be some dependencies in setup.py that needs an update #660. QT5 is also outdated and is generally a problem that we need to look into #551.

**Comment by razmy-hathy** [comment]
Thanks for the prompt reply. I have managed to fix above issue by installing Qt by "brew install pyqt5". However, I'm stuck with a different error. Please see below given error log.


pip3 install cfclient
Collecting cfclient
  Using cached cfclient-2023.2-py3-none-any.whl (307 kB)
Collecting cflib>=0.1.22
  Using cached cflib-0.1.22-py2.py3-none-any.whl (185 kB)
Collecting appdirs~=1.4.0
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting pyzmq~=22.3
  Using cached pyzmq-22.3.0.tar.gz (1.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pyqtgraph~=0.11
  Using cached pyqtgraph-0.13.2-py3-none-any.whl (955 kB)
Collecting PyYAML~=5.3
  Using cached PyYAML-5.4.1-cp311-cp311-macosx_13_0_arm64.whl
Collecting qasync~=0.23.0
  Using cached qasync-0.23.0-py3-none-any.whl (13 kB)
Collecting qtm~=2.1.1
  Using cached qtm-2.1.1-py3-none-any.whl (3.1 MB)
Collecting numpy<1.25,>=1.20
  Using cached numpy-1.24.2-cp311-cp311-macosx_11_0_arm64.whl (13.8 MB)
Collecting vispy~=0.9.0
  Using cached vispy-0.9.6-cp311-cp311-macosx_13_0_arm64.whl
Collecting pyserial~=3.5
  Using cached pyserial-3.5-py2.py3-none-any.whl (90 kB)
Requirement already satisfied: pyqt5~=5.15.0 in /opt/homebrew/lib/python3.11/site-packages (from cfclient) (5.15.7)
Requirement already satisfied: PyQt5-sip>=12.9.0 in /opt/homebrew/lib/python3.11/site-packages (from cfclient) (12.11.0)
Collecting pysdl2~=0.9.14
  Using cached PySDL2-0.9.15-py3-none-any.whl
Collecting pysdl2-dll==2.24.0
  Using cached pysdl2_dll-2.24.0-py2.py3-none-macosx_10_7_universal2.whl (4.9 MB)
Collecting pyusb>=1.0.0b2
  Using cached pyusb-1.2.1-py3-none-any.whl (58 kB)
Collecting libusb-package~=1.0
  Using cached libusb_package-1.0.26.1-cp311-cp311-macosx_11_0_arm64.whl (60 kB)
Collecting scipy~=1.7
  Using cached scipy-1.10.1-cp311-cp311-macosx_12_0_arm64.whl (28.7 MB)
Collecting freetype-py
  Using cached freetype_py-2.3.0-py3-none-macosx_10_9_universal2.whl (1.7 MB)
Collecting hsluv
  Using cached hsluv-5.0.3-py2.py3-none-any.whl (5.1 kB)
Collecting kiwisolver
  Using cached kiwisolver-1.4.4-cp311-cp311-macosx_11_0_arm64.whl (63 kB)
Building wheels for collected packages: pyzmq
  Building wheel for pyzmq (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for pyzmq (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [184 lines of output]
      /opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/_distutils/dist.py:265: UserWarning: Unknown distribution option: 'cffi_modules'
        warnings.warn(msg)
      running bdist_wheel
      running build
      running build_py
      creating build/lib.macosx-13-arm64-cpython-311
      creating build/lib.macosx-13-arm64-cpython-311/zmq
      copying zmq/error.py -> build/lib.macosx-13-arm64-cpython-311/zmq
      copying zmq/_future.py -> build/lib.macosx-13-arm64-cpython-311/zmq
      copying zmq/asyncio.py -> build/lib.macosx-13-arm64-cpython-311/zmq
      copying zmq/__init__.py -> build/lib.macosx-13-arm64-cpython-311/zmq
      copying zmq/decorators.py -> build/lib.macosx-13-arm64-cpython-311/zmq
      creating build/lib.macosx-13-arm64-cpython-311/zmq/green
      copying zmq/green/device.py -> build/lib.macosx-13-arm64-cpython-311/zmq/green
      copying zmq/green/__init__.py -> build/lib.macosx-13-arm64-cpython-311/zmq/green
      copying zmq/green/core.py -> build/lib.macosx-13-arm64-cpython-311/zmq/green
      copying zmq/green/poll.py -> build/lib.macosx-13-arm64-cpython-311/zmq/green
      creating build/lib.macosx-13-arm64-cpython-311/zmq/green/eventloop
      copying zmq/green/eventloop/__init__.py -> build/lib.macosx-13-arm64-cpython-311/zmq/green/eventloop
      copying zmq/green/eventloop/ioloop.py -> build/lib.macosx-13-arm64-cpython-311/zmq/green/eventloop
      copying zmq/green/eventloop/zmqstream.py -> build/lib.macosx-13-arm64-cpython-311/zmq/green/eventloop
      creating build/lib.macosx-13-arm64-cpython-311/zmq/sugar
      copying zmq/sugar/version.py -> build/lib.macosx-13-arm64-cpython-311/zmq/sugar
      copying zmq/sugar/attrsettr.py -> build/lib.macosx-13-arm64-cpython-311/zmq/sugar
      copying zmq/sugar/constants.py -> build/lib.macosx-13-arm64-cpython-311/zmq/sugar
      copying zmq/sugar/__init__.py -> build/lib.macosx-13-arm64-cpython-311/zmq/sugar
      copying zmq/sugar/stopwatch.py -> build/lib.macosx-13-arm64-cpython-311/zmq/sugar
      copying zmq/sugar/context.py -> build/lib.macosx-13-arm64-cpython-311/zmq/sugar
      copying zmq/sugar/frame.py -> build/lib.macosx-13-arm64-cpython-311/zmq/sugar
      copying zmq/sugar/tracker.py -> build/lib.macosx-13-arm64-cpython-311/zmq/sugar
      copying zmq/sugar/poll.py -> build/lib.macosx-13-arm64-cpython-311/zmq/sugar
      copying zmq/sugar/socket.py -> build/lib.macosx-13-arm64-cpython-311/zmq/sugar
      creating build/lib.macosx-13-arm64-cpython-311/zmq/auth
      copying zmq/auth/thread.py -> build/lib.macosx-13-arm64-cpython-311/zmq/auth
      copying zmq/auth/certs.py -> build/lib.macosx-13-arm64-cpython-311/zmq/auth
      copying zmq/auth/asyncio.py -> build/lib.macosx-13-arm64-cpython-311/zmq/auth
      copying zmq/auth/__init__.py -> build/lib.macosx-13-arm64-cpython-311/zmq/auth
      copying zmq/auth/ioloop.py -> build/lib.macosx-13-arm64-cpython-311/zmq/auth
      copying zmq/auth/base.py -> build/lib.macosx-13-arm64-cpython-311/zmq/auth
      creating build/lib.macosx-13-arm64-cpython-311/zmq/tests
      copying zmq/tests/test_ioloop.py -> build/lib.macosx-13-arm64-cpython-311/zmq/tests
      copying zmq/tests/test_version.py -> build/lib.macosx-13-arm64-cpython-311/zmq/tests
      copying zmq/tests/test_monitor.py -> build/lib.macosx-13-arm64-cpython-311/zmq/tests
      copying zmq/tests/test_security.py -> build/lib.macosx-13-arm64-cpython-311/zmq/tests
      copying zmq/tests/conftest.py -> build/lib.macosx-13-arm64-cpython-311/zmq/tests
      copying zmq/tests/test_decorators.py -> build/lib.macosx-13-arm64-cpython-311/zmq/tests
      copying zmq/tests/test_etc.py -> build/lib.macosx-13-arm64-cpython-311/zmq/tests
      copying zmq/tests/test_pubsub.py -> build/lib.macosx-13-arm64-cpython-311/zmq/tests
      copying zmq/tests/test_auth.py -> build/lib.macosx-13-arm64-cpython-311/zmq/tests
      copying zmq/tests/test_includes.py -> build/lib.macosx-13-arm64-cpython-311/zmq/tests
      copying zmq/tests/test_mypy.py -> build/lib.macosx-13-arm64-cpython-311/zmq/tests
      copying zmq/tests/test_future.py -> build/lib.macosx-13-arm64-cpython-311/zmq/tests
      copying zmq/tests/test_zmqstream.py -> build/lib.macosx-13-arm64-cpython-311/zmq/tests
      copying zmq/tests/test_message.py -> build/lib.macosx-13-arm64-cpython-311/zmq/tests
      copying zmq/tests/test_cffi_backend.py -> build/lib.macosx-13-arm64-cpython-311/zmq/tests
      copying zmq/tests/test_imports.py -> build/lib.macosx-13-arm64-cpython-311/zmq/tests
      copying zmq/tests/test_socket.py -> build/lib.macosx-13-arm64-cpython-311/zmq/tests
      copying zmq/tests/test_draft.py -> build/lib.macosx-13-arm64-cpython-311/zmq/tests
      copying zmq/tests/__init__.py -> build/lib.macosx-13-arm64-cpython-311/zmq/tests
      copying zmq/tests/test_asyncio.py -> build/lib.macosx-13-arm64-cpython-311/zmq/tests
      copying zmq/tests/test_log.py -> build/lib.macosx-13-arm64-cpython-311/zmq/tests
      copying zmq/tests/test_ssh.py -> build/lib.macosx-13-arm64-cpython-311/zmq/tests
      copying zmq/tests/test_cython.py -> build/lib.macosx-13-arm64-cpython-311/zmq/tests
      copying zmq/tests/test_retry_eintr.py -> build/lib.macosx-13-arm64-cpython-311/zmq/tests
      copying zmq/tests/test_z85.py -> build/lib.macosx-13-arm64-cpython-311/zmq/tests
      copying zmq/tests/test_error.py -> build/lib.macosx-13-arm64-cpython-311/zmq/tests
      copying zmq/tests/test_reqrep.py -> build/lib.macosx-13-arm64-cpython-311/zmq/tests
      copying zmq/tests/test_multipart.py -> build/lib.macosx-13-arm64-cpython-311/zmq/tests
      copying zmq/tests/test_context.py -> build/lib.macosx-13-arm64-cpython-311/zmq/tests
      copying zmq/tests/test_proxy_steerable.py -> build/lib.macosx-13-arm64-cpython-311/zmq/tests
      copying zmq/tests/test_device.py -> build/lib.macosx-13-arm64-cpython-311/zmq/tests
      copying zmq/tests/test_pair.py -> build/lib.macosx-13-arm64-cpython-311/zmq/tests
      copying zmq/tests/test_constants.py -> build/lib.macosx-13-arm64-cpython-311/zmq/tests
      copying zmq/tests/test_monqueue.py -> build/lib.macosx-13-arm64-cpython-311/zmq/tests
      copying zmq/tests/test_poll.py -> build/lib.macosx-13-arm64-cpython-311/zmq/tests
      copying zmq/tests/test_win32_shim.py -> build/lib.macosx-13-arm64-cpython-311/zmq/tests
      creating build/lib.macosx-13-arm64-cpython-311/zmq/utils
      copying zmq/utils/strtypes.py -> build/lib.macosx-13-arm64-cpython-311/zmq/utils
      copying zmq/utils/monitor.py -> build/lib.macosx-13-arm64-cpython-311/zmq/utils
      copying zmq/utils/__init__.py -> build/lib.macosx-13-arm64-cpython-311/zmq/utils
      copying zmq/utils/win32.py -> build/lib.macosx-13-arm64-cpython-311/zmq/utils
      copying zmq/utils/constant_names.py -> build/lib.macosx-13-arm64-cpython-311/zmq/utils
      copying zmq/utils/interop.py -> build/lib.macosx-13-arm64-cpython-311/zmq/utils
      copying zmq/utils/jsonapi.py -> build/lib.macosx-13-arm64-cpython-311/zmq/utils
      copying zmq/utils/z85.py -> build/lib.macosx-13-arm64-cpython-311/zmq/utils
      copying zmq/utils/garbage.py -> build/lib.macosx-13-arm64-cpython-311/zmq/utils
      creating build/lib.macosx-13-arm64-cpython-311/zmq/backend
      copying zmq/backend/__init__.py -> build/lib.macosx-13-arm64-cpython-311/zmq/backend
      copying zmq/backend/select.py -> build/lib.macosx-13-arm64-cpython-311/zmq/backend
      creating build/lib.macosx-13-arm64-cpython-311/zmq/backend/cffi
      copying zmq/backend/cffi/_poll.py -> build/lib.macosx-13-arm64-cpython-311/zmq/backend/cffi
      copying zmq/backend/cffi/error.py -> build/lib.macosx-13-arm64-cpython-311/zmq/backend/cffi
      copying zmq/backend/cffi/constants.py -> build/lib.macosx-13-arm64-cpython-311/zmq/backend/cffi
      copying zmq/backend/cffi/__init__.py -> build/lib.macosx-13-arm64-cpython-311/zmq/backend/cffi
      copying zmq/backend/cffi/message.py -> build/lib.macosx-13-arm64-cpython-311/zmq/backend/cffi
      copying zmq/backend/cffi/context.py -> build/lib.macosx-13-arm64-cpython-311/zmq/backend/cffi
      copying zmq/backend/cffi/utils.py -> build/lib.macosx-13-arm64-cpython-311/zmq/backend/cffi
      copying zmq/backend/cffi/socket.py -> build/lib.macosx-13-arm64-cpython-311/zmq/backend/cffi
      copying zmq/backend/cffi/devices.py -> build/lib.macosx-13-arm64-cpython-311/zmq/backend/cffi
      creating build/lib.macosx-13-arm64-cpython-311/zmq/backend/cython
      copying zmq/backend/cython/__init__.py -> build/lib.macosx-13-arm64-cpython-311/zmq/backend/cython
      creating build/lib.macosx-13-arm64-cpython-311/zmq/ssh
      copying zmq/ssh/__init__.py -> build/lib.macosx-13-arm64-cpython-311/zmq/ssh
      copying zmq/ssh/tunnel.py -> build/lib.macosx-13-arm64-cpython-311/zmq/ssh
      copying zmq/ssh/forward.py -> build/lib.macosx-13-arm64-cpython-311/zmq/ssh
      creating build/lib.macosx-13-arm64-cpython-311/zmq/eventloop
      copying zmq/eventloop/_deprecated.py -> build/lib.macosx-13-arm64-cpython-311/zmq/eventloop
      copying zmq/eventloop/__init__.py -> build/lib.macosx-13-arm64-cpython-311/zmq/eventloop
      copying zmq/eventloop/ioloop.py -> build/lib.macosx-13-arm64-cpython-311/zmq/eventloop
      copying zmq/eventloop/future.py -> build/lib.macosx-13-arm64-cpython-311/zmq/eventloop
      copying zmq/eventloop/zmqstream.py -> build/lib.macosx-13-arm64-cpython-311/zmq/eventloop
      creating build/lib.macosx-13-arm64-cpython-311/zmq/eventloop/minitornado
      copying zmq/eventloop/minitornado/concurrent.py -> build/lib.macosx-13-arm64-cpython-311/zmq/eventloop/minitornado
      copying zmq/eventloop/minitornado/stack_context.py -> build/lib.macosx-13-arm64-cpython-311/zmq/eventloop/minitornado
      copying zmq/eventloop/minitornado/log.py -> build/lib.macosx-13-arm64-cpython-311/zmq/eventloop/minitornado
      copying zmq/eventloop/minitornado/util.py -> build/lib.macosx-13-arm64-cpython-311/zmq/eventloop/minitornado
      copying zmq/eventloop/minitornado/__init__.py -> build/lib.macosx-13-arm64-cpython-311/zmq/eventloop/minitornado
      copying zmq/eventloop/minitornado/ioloop.py -> build/lib.macosx-13-arm64-cpython-311/zmq/eventloop/minitornado
      creating build/lib.macosx-13-arm64-cpython-311/zmq/eventloop/minitornado/platform
      copying zmq/eventloop/minitornado/platform/interface.py -> build/lib.macosx-13-arm64-cpython-311/zmq/eventloop/minitornado/platform
      copying zmq/eventloop/minitornado/platform/__init__.py -> build/lib.macosx-13-arm64-cpython-311/zmq/eventloop/minitornado/platform
      copying zmq/eventloop/minitornado/platform/common.py -> build/lib.macosx-13-arm64-cpython-311/zmq/eventloop/minitornado/platform
      copying zmq/eventloop/minitornado/platform/posix.py -> build/lib.macosx-13-arm64-cpython-311/zmq/eventloop/minitornado/platform
      copying zmq/eventloop/minitornado/platform/windows.py -> build/lib.macosx-13-arm64-cpython-311/zmq/eventloop/minitornado/platform
      copying zmq/eventloop/minitornado/platform/auto.py -> build/lib.macosx-13-arm64-cpython-311/zmq/eventloop/minitornado/platform
      creating build/lib.macosx-13-arm64-cpython-311/zmq/log
      copying zmq/log/handlers.py -> build/lib.macosx-13-arm64-cpython-311/zmq/log
      copying zmq/log/__init__.py -> build/lib.macosx-13-arm64-cpython-311/zmq/log
      copying zmq/log/__main__.py -> build/lib.macosx-13-arm64-cpython-311/zmq/log
      creating build/lib.macosx-13-arm64-cpython-311/zmq/devices
      copying zmq/devices/monitoredqueue.py -> build/lib.macosx-13-arm64-cpython-311/zmq/devices
      copying zmq/devices/__init__.py -> build/lib.macosx-13-arm64-cpython-311/zmq/devices
      copying zmq/devices/monitoredqueuedevice.py -> build/lib.macosx-13-arm64-cpython-311/zmq/devices
      copying zmq/devices/proxydevice.py -> build/lib.macosx-13-arm64-cpython-311/zmq/devices
      copying zmq/devices/basedevice.py -> build/lib.macosx-13-arm64-cpython-311/zmq/devices
      copying zmq/devices/proxysteerabledevice.py -> build/lib.macosx-13-arm64-cpython-311/zmq/devices
      copying zmq/__init__.pxd -> build/lib.macosx-13-arm64-cpython-311/zmq
      copying zmq/__init__.pyi -> build/lib.macosx-13-arm64-cpython-311/zmq
      copying zmq/py.typed -> build/lib.macosx-13-arm64-cpython-311/zmq
      copying zmq/sugar/__init__.pyi -> build/lib.macosx-13-arm64-cpython-311/zmq/sugar
      copying zmq/sugar/constants.pyi -> build/lib.macosx-13-arm64-cpython-311/zmq/sugar
      copying zmq/utils/buffers.pxd -> build/lib.macosx-13-arm64-cpython-311/zmq/utils
      copying zmq/utils/zmq_constants.h -> build/lib.macosx-13-arm64-cpython-311/zmq/utils
      copying zmq/utils/getpid_compat.h -> build/lib.macosx-13-arm64-cpython-311/zmq/utils
      copying zmq/utils/pyversion_compat.h -> build/lib.macosx-13-arm64-cpython-311/zmq/utils
      copying zmq/utils/zmq_compat.h -> build/lib.macosx-13-arm64-cpython-311/zmq/utils
      copying zmq/utils/mutex.h -> build/lib.macosx-13-arm64-cpython-311/zmq/utils
      copying zmq/utils/ipcmaxlen.h -> build/lib.macosx-13-arm64-cpython-311/zmq/utils
      copying zmq/utils/config.json -> build/lib.macosx-13-arm64-cpython-311/zmq/utils
      copying zmq/utils/compiler.json -> build/lib.macosx-13-arm64-cpython-311/zmq/utils
      copying zmq/backend/__init__.pyi -> build/lib.macosx-13-arm64-cpython-311/zmq/backend
      copying zmq/backend/constants.pyi -> build/lib.macosx-13-arm64-cpython-311/zmq/backend
      copying zmq/backend/cffi/_cdefs.h -> build/lib.macosx-13-arm64-cpython-311/zmq/backend/cffi
      copying zmq/backend/cython/message.pxd -> build/lib.macosx-13-arm64-cpython-311/zmq/backend/cython
      copying zmq/backend/cython/libzmq.pxd -> build/lib.macosx-13-arm64-cpython-311/zmq/backend/cython
      copying zmq/backend/cython/checkrc.pxd -> build/lib.macosx-13-arm64-cpython-311/zmq/backend/cython
      copying zmq/backend/cython/__init__.pxd -> build/lib.macosx-13-arm64-cpython-311/zmq/backend/cython
      copying zmq/backend/cython/context.pxd -> build/lib.macosx-13-arm64-cpython-311/zmq/backend/cython
      copying zmq/backend/cython/socket.pxd -> build/lib.macosx-13-arm64-cpython-311/zmq/backend/cython
      copying zmq/backend/cython/constant_enums.pxi -> build/lib.macosx-13-arm64-cpython-311/zmq/backend/cython
      copying zmq/backend/cython/constants.pxi -> build/lib.macosx-13-arm64-cpython-311/zmq/backend/cython
      copying zmq/devices/monitoredqueue.pxd -> build/lib.macosx-13-arm64-cpython-311/zmq/devices
      running build_ext
      running configure
      Settings obtained from pkg-config: {'library_dirs': ['/opt/homebrew/Cellar/zeromq/4.3.4/lib'], 'include_dirs': ['/opt/homebrew/Cellar/zeromq/4.3.4/include', '/opt/homebrew/Cellar/libsodium/1.0.18_1/include'], 'libraries': ['zmq']}
      {'libraries': ['zmq'], 'include_dirs': ['/opt/homebrew/Cellar/zeromq/4.3.4/include', '/opt/homebrew/Cellar/libsodium/1.0.18_1/include'], 'library_dirs': ['/opt/homebrew/Cellar/zeromq/4.3.4/lib'], 'runtime_library_dirs': [], 'extra_link_args': ['-Wl,-rpath', '-Wl,/opt/homebrew/Cellar/zeromq/4.3.4/lib']}
      Configure: Autodetecting ZMQ settings...
          Custom ZMQ dir:
      clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -I/opt/homebrew/Cellar/zeromq/4.3.4/include -I/opt/homebrew/Cellar/libsodium/1.0.18_1/include -Izmq/utils -c build/temp.macosx-13-arm64-cpython-311/scratch/vers.c -o build/temp.macosx-13-arm64-cpython-311/scratch/vers.o
      clang -undefined dynamic_lookup -Wl,-rpath -Wl,/opt/homebrew/Cellar/zeromq/4.3.4/lib build/temp.macosx-13-arm64-cpython-311/scratch/vers.o -L/opt/homebrew/Cellar/zeromq/4.3.4/lib -lzmq -o build/temp.macosx-13-arm64-cpython-311/scratch/vers
      ld: warning: -undefined dynamic_lookup may not work with chained fixups
          ZMQ version detected: 4.3.4
      building 'zmq.backend.cython._device' extension
      creating build/temp.macosx-13-arm64-cpython-311/zmq
      creating build/temp.macosx-13-arm64-cpython-311/zmq/backend
      creating build/temp.macosx-13-arm64-cpython-311/zmq/backend/cython
      clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -DHAVE_SYS_UN_H=1 -I/opt/homebrew/Cellar/zeromq/4.3.4/include -I/opt/homebrew/Cellar/libsodium/1.0.18_1/include -Izmq/utils -I/opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c zmq/backend/cython/_device.c -o build/temp.macosx-13-arm64-cpython-311/zmq/backend/cython/_device.o
      zmq/backend/cython/_device.c:217:12: fatal error: 'longintrepr.h' file not found
        #include "longintrepr.h"
                 ^~~~~~~~~~~~~~~
      1 error generated.
      ************************************************
      ************************************************
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyzmq
Failed to build pyzmq
ERROR: Could not build wheels for pyzmq, which is required to install pyproject.toml-based projects

**Comment by krichardsson** [comment]
See #660

**Comment by krichardsson** [comment]
@razmy-hathy #660 has been fixed now. Please retest to see if it solved your problem.
Note, we have not made a release, you have to close the git repo and run from source.

**Comment by knmcguire** [comment]
So this needs to be tested with the next release anyway! then we will know if this has been resolved or not.

**Comment by krichardsson** [comment]
Works on our MacBook Air, M1, MacOS 13.4
Closing
