### ISSUE TITLE
Client does not run on Windows 10

### ISSUE THREAD

**Issue by mbaytas** [bitcraze/crazyflie-clients-python#381]
I have Windows 10 Pro (10.0.17134 Build 17134), no Python installed on system. Installed Crazyflie client 2019.01 from release (cfclient-win32-install-2019.01.exe).

When launching "crazyflie PC Client" from Start Menu, a window opens and disappears immediately.

When launching from Command Prompt:

    C:\>"C:\Program Files (x86)\Crazyflie client\cfclient.exe"
    Traceback (most recent call last):
      File "C:\Python36\lib\asyncio\__init__.py", line 9, in <module>
    ImportError: cannot import name 'selectors'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Python36\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
      File "C:\Python36\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
      File "bin/cfclient", line 2, in <module>
      File "c:\projects\crazyflie-clients-python\src\cfclient\gui.py", line 31, in <module>
      File "C:\Python36\lib\asyncio\__init__.py", line 11, in <module>
      File "C:\Python36\lib\selectors.py", line 11, in <module>
    ImportError: Module use of python34.dll conflicts with this version of Python.

Reminder: I don't have a system Python. See:

    C:\>cd Python36
    The system cannot find the path specified.

**Comment by ataffanel** [comment]
Are you sure there is no python installed? The client is built against Python 3.6 and I just tried the 2019.01 build on a fresh Windows 10 1903 and is works fine.

Anyway, it should not be a problem even with another version of Python installed. I am currently working on fixing a Windows release for 2019.10, lets test that one when I push it and see if you still have the problem.

**Comment by tharindusuraj** [comment]
I'm getting the same error with the latest version. I have python 2.7 and 3.7 installed on windows 8.

**Comment by ataffanel** [comment]
@tharindusuraj What error are you seeing exactly when running the executable from the windows build installer? Are you using cfclient-win32-install-2019.09.1.exe from https://github.com/bitcraze/crazyflie-clients-python/releases/tag/2019.09.1?

**Comment by tharindusuraj** [comment]
Yes I'm using the latest CF client installer.
![CF PC client error](https://user-images.githubusercontent.com/28068897/69241906-c7657780-0bc5-11ea-8416-a7de0f7bd0b4.jpg)

**Comment by ataffanel** [comment]
This might be a problem caused when upgrading the client. Can you try to remove it completly (by running the uninstalled AND removing the crazyflie-client folder in c:\Program Files (x86)) and then re-installing it. It should solve this issue.

**Comment by knmcguire** [comment]
@tharindusuraj   Has @ataffanel 's suggestion solved your issue?

**Comment by krichardsson** [comment]
Closed due to inactivity
