### ISSUE TITLE
Connecting using usb://0 fails on official ubuntu 15.04 due to pyusb package being 0.4.3

### ISSUE THREAD

**Issue by tobbeanton** [bitcraze/crazyflie-clients-python#183]
Error displayed in client:
```
Failed to connect on usb://0: Error communicating with the Crazyflie ,it has probably been unplugged!
Exception:'USBError' object has no attribute 'backend_error_code'

Traceback (most recent call last):
  File "/home/anton/projects/workspace/crazyflie-clients-python/lib/cflib/crtp/usbdriver.py", line 245, in run
    data = self.cfusb.receive_packet()
  File "/home/anton/projects/workspace/crazyflie-clients-python/lib/cflib/drivers/cfusb.py", line 162, in receive_packet
    if e.backend_error_code == -7:
AttributeError: 'USBError' object has no attribute 'backend_error_code'
```
Workaround:
Install pyusb version 1.0.0a3 with:
```
sudo apt-get remove python-usb
sudo pip install pyusb==1.0.0a3
```

**Comment by evoggy** [comment]
This should work with any version above 1.0. With the workaround in cb452e5 it's possible use the USB with pyusb < 1.0, but it's not possible to detect when the USB is disconnected by pulling the cable.
